#Website Settings
title: Hake Blog
email: test@test.com
linkedin: 
description: "The personal blog of Sam Scott-Hake"

# Build settings

markdown: kramdown
permalink: pretty

port: 4000 

sass:
  sass_dir: assets/css
  style: :nested